### ISSUE TITLE
Which version / branch

### ISSUE THREAD

**Issue by martiliasf** [adavtyan/awsemmd#2]
Hello - 

I'm trying to predict the structure of a protein with 13 TM domains. I was hoping to use awsem-membrane, but I'm having trouble figuring out which version I should dload / compile etc. Does the main branch have the membrane code, or should I goto the membrane branch?

Thanks,
Marty

**Comment by adavtyan** [comment]
You should use the membrane branch. The main branch does not have the membrane capabilities.
