### ISSUE TITLE
Atom_Style Peptide Missing

### ISSUE THREAD

**Issue by lumpthree** [adavtyan/awsemmd#3]
The peptide atom_style was removed in May 2016, but "inFilePattern.data" still uses the peptide atom_style, resulting in an "Unknown atom style" error upon running lmp_serial with a ".in" file generated by "PDBCoords2LAMMPS.sh".

**Comment by adavtyan** [comment]
The awsemmd atom style must be used instead. The patch to PDBCoords2LAMMPS has been applied.
